#!/bin/bash -l
# Name of job
#SBATCH -J lab1
#SBATCH -A edu26.dd2443
# Reservation if needed
#SBATCH -t 00:50:00
#SBATCH -p shared
#SBATCH -n 1
#SBATCH -c 64
# load modules and run
ml java/21
srun ./run.sh > task2_6.dat